# Header
menu:
  博客主页: /
  全部文章: /archives
rss: /atom.xml

# Content
excerpt_link: 进入阅读
fancybox: true

# Sidebar
sidebar: right
widgets:
- category
- tag
- tagcloud
- archive
- recent_posts

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
archive_type: 'monthly'
show_count: true

# Miscellaneous
google_analytics:
favicon: /blog/favicon.png
twitter:
google_plus:
fb_admins:
fb_app_id:
